export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SAVE_RICH_TEST = 'SAVE_RICH_TEST';
export const UPDATE_RICH_TEST_PROPS = 'UPDATE_RICH_TEST_PROPS';
export const GENERATE_BTC_ADDRESS_SUCCESS = 'GENERATE_BTC_ADDRESS_SUCCESS';
export const ADD_NEW_ADDRESS_SUCCESS = 'ADD_NEW_ADDRESS';

export const SAGA_GENERATE_BTC_ACCOUNT_BEGIN = 'SAGA_GENERATE_BTC_ACCOUNT_BEGIN';
export const SAGA_GENERATE_BTC_ACCOUNT_SUCCESS = 'SAGA_GENERATE_BTC_ACCOUNT_SUCCESS';
export const SAGA_GENERATE_BTC_ACCOUNT_ERROR = 'SAGA_GENERATE_BTC_ACCOUNT_ERROR';

export const SAGA_GENERATE_BTC_ADDRESS_BEGIN = 'SAGA_GENERATE_BTC_ADDRESS_BEGIN';
export const SAGA_GENERATE_BTC_ADDRESS_SUCCESS = 'SAGA_GENERATE_BTC_ADDRESS_SUCCESS';
export const SAGA_GENERATE_BTC_ADDRESS_ERROR = 'SAGA_GENERATE_BTC_ADDRESS_ERROR';
