export const SAVE_FUEL_SAVINGS = 'SAVE_FUEL_SAVINGS';
export const CALCULATE_FUEL_SAVINGS = 'CALCULATE_FUEL_SAVINGS';
export const SAVE_RICH_TEST = 'SAVE_RICH_TEST';
export const UPDATE_RICH_TEST_PROPS = 'UPDATE_RICH_TEST_PROPS';
